server:
  port: 8082
spring:
  application:
    name: service-timetable
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://42.192.226.66:3306/mind_wings?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: remote
    password: wds20010821
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  configuration:
    map-underscore-to-camel-case: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
mybatis:
  configuration:
    map-underscore-to-camel-case: true